# Generated by Django 5.0 on 2024-01-20 12:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=200, null=True)),
                ('texte', models.TextField(max_length=200, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('membre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membre.membre')),
            ],
        ),
    ]
