# Generated by Django 5.0 on 2024-01-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlanguage',
            name='language',
            field=models.CharField(choices=[('fr', 'English'), ('en', 'Français')], max_length=5, verbose_name='Language'),
        ),
    ]
