# Generated by Django 5.0 on 2024-01-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0002_alter_userlanguage_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlanguage',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français')], max_length=5, verbose_name='Language'),
        ),
    ]
