# Generated by Django 5.0 on 2024-03-13 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumAtt', models.IntegerField(default=0, null=True)),
                ('cumVers', models.IntegerField(default=0, null=True)),
                ('ecart', models.IntegerField(blank=True, null=True)),
                ('sortie', models.IntegerField(default=0, null=True)),
                ('motif', models.CharField(max_length=200, null=True)),
                ('membre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='membre.membre')),
            ],
        ),
    ]
