# Generated by Django 5.0 on 2024-01-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etat',
            name='ecart',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
