# Generated by Django 5.0 on 2024-01-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etat', '0003_alter_etat_ecart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etat',
            name='ecart',
            field=models.CharField(choices=[('gt', 'Supérieur à'), ('lt', 'Inférieur à'), ('eq', 'Egal à')], max_length=200, null=True),
        ),
    ]
