# Generated by Django 5.0 on 2024-01-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etat', '0004_alter_etat_ecart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etat',
            name='ecart',
            field=models.IntegerField(null=True),
        ),
    ]
