# Generated by Django 5.0 on 2024-01-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profil_picture',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
