# Generated by Django 5.0 on 2024-01-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_alter_userprofile_profil_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profil_picture',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
