# Generated by Django 5.0 on 2024-01-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('matricule', models.CharField(max_length=200, null=True)),
                ('region', models.CharField(choices=[('Adamaoua', 'Adamaoua'), ('Centre', 'Centre'), ('Est', 'Est'), ('Extreme-Nord', 'Extreme-Nord'), ('Littoral', 'Littoral'), ('Nord', 'Nord'), ('Nord-Ouest', 'Nord-Ouest'), ('Ouest', 'Ouest'), ('Sud', 'Sud'), ('Sud-Ouest', 'Sud-Ouest')], max_length=200, null=True)),
                ('departement', models.CharField(max_length=200, null=True)),
                ('etablissement', models.CharField(max_length=200, null=True)),
                ('discipline', models.CharField(max_length=200, null=True)),
                ('telephone', models.IntegerField(null=True)),
                ('ajour', models.CharField(choices=[('Ajour', 'Ajour'), ('Pas Ajour', 'Pas Ajour')], max_length=200, null=True)),
                ('actif', models.CharField(choices=[('Actif', 'Actif'), ('Pas Actif', 'Pas Actif')], max_length=200, null=True)),
            ],
        ),
    ]
