# Generated by Django 5.0 on 2024-03-13 05:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('matricule', models.CharField(max_length=200, null=True)),
                ('region', models.CharField(choices=[('Adamaoua', 'Adamaoua'), ('Centre', 'Centre'), ('Est', 'Est'), ('Extreme-Nord', 'Extreme-Nord'), ('Littoral', 'Littoral'), ('Nord', 'Nord'), ('Nord-Ouest', 'Nord-Ouest'), ('Ouest', 'Ouest'), ('Sud', 'Sud'), ('Sud-Ouest', 'Sud-Ouest')], max_length=200, null=True)),
                ('departement', models.CharField(choices=[('Vina', 'Vina'), ('Djérem', 'Djérem'), ('Faro-et-Déo', 'Faro-et-Déo'), ('Mayo-Banyo', 'Mayo-Banyo'), ('Mbéré', 'Mbéré')], max_length=200, null=True)),
                ('etablissement', models.CharField(choices=[('DRES', 'DRES'), ('Lycée classique de Ngaoundére', 'Lycée classique de Ngaoundére'), ('Lycée Bilingue de Ngaoundére', 'Lycée Bilingue de Ngaoundére'), ('Lycée de Ngaoundére Mardock', 'Lycée de Ngaoundére Mardock'), ('Collège Polyvalent Bilingue la Victoire', 'Collège Polyvalent Bilingue la Victoire'), ('Institut Polyvalent Bilingue le Pintades', 'Institut Polyvalent Bilingue le Pintades'), ('Lycée de Burkina', 'Lycée de Burkina')], max_length=200, null=True)),
                ('discipline', models.CharField(choices=[('Mathématiques', 'Mathématiques'), ('Informatique', 'Informatique'), ('PCT', 'PCT'), ('Francais', 'Francais'), ('HGE', 'HGE'), ('Anglais', 'Anglais')], max_length=200, null=True)),
                ('telephone', models.IntegerField(null=True)),
                ('dateService', models.DateField(null=True)),
                ('dateInscription', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('ajour', models.CharField(max_length=200, null=True)),
                ('actif', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PointFocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
