# Generated by Django 5.0 on 2024-01-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='departement',
            field=models.CharField(choices=[('Vina', 'Vina'), ('Djerem', 'Djerem')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='discipline',
            field=models.CharField(choices=[('Mathematiques', 'Mathematiques'), ('Informatique', 'Informatique'), ('Physique', 'Physique')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='etablissement',
            field=models.CharField(choices=[('DRES', 'DRES'), ('Lycée classique', 'Lycée classique'), ('Lycée bilingue', 'Lycée bilingue')], max_length=200, null=True),
        ),
    ]
